### ISSUE TITLE
Support MRI (and others)

### ISSUE THREAD

**Issue by stereobooster** [txus/explain#1]
What about [melbourne gem](https://github.com/simplabs/melbourne) by simplabs  or [melbourne gem](https://github.com/rubinius/melbourne) by rubinius?

**Comment by txus** [comment]
Great! I wasn't aware that melbourne was already extracted! Want to give it a try switching to the gem @stereobooster ?

**Comment by stereobooster** [comment]
Not sure if I have enough time. I already have some projects in my todo list

**Comment by txus** [comment]
No problem, I'll do it then :)
